config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'membership' => 'static_pages#membership'
  get 'opening-times' => 'static_pages#times'
  get 'contact' => 'static_pages#contact'
  get 'classes' => 'static_pages#classes'
  get 'gym-facilities' => 'static_pages#facilities'

  get 'classes/ab-solution' => 'static_pages#ab_solution'
  get 'classes/bootcamp' => 'static_pages#bootcamp'
  get 'classes/boxing' => 'static_pages#boxing'
  get 'classes/circuit-training' => 'static_pages#circuit_training'
  get 'classes/cycle-fit' => 'static_pages#cycle_fit'
  get 'classes/cycle-pump' => 'static_pages#cycle_pump'
  get 'classes/hiit' => 'static_pages#hiit'
  get 'classes/kettle-x-fit' => 'static_pages#kettle_x_fit'
  get 'classes/lbt' => 'static_pages#lbt'
  get 'classes/mma' => 'static_pages#mma'
  get 'classes/pilates' => 'static_pages#pilates'
  get 'classes/pilates_hiit' => 'static_pages#pilates_hiit'
  get 'classes/pumped' => 'static_pages#pumped'
  get 'classes/rig_assault' => 'static_pages#rig_assault'
  get 'classes/s_and_c' => 'static_pages#s_and_c'
  get 'classes/total_body' => 'static_pages#total_body'
  get 'classes/trx' => 'static_pages#trx'
  get 'classes/ultimate_endurance' => 'static_pages#ultimate_endurance'

  get 'personal-training' => 'static_pages#personal_training'

end

app/views/layouts/_backend_nav.html.erb
<div id="nav-wrapper">
  <div id="nav" class="row">
  <div class="small-12 columns">
    <img src="http://www.visionhealthandfitness.co.uk/logo-small.png" alt="Vision Health and Fitness logo">
  </div>
    
  </div>
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>
    <section class="top-bar-section">
      <% if logged_in? %>
      <ul class="right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Customers", backend_customers_path %></li>
        <li><%= link_to "Blowouts", backend_blowouts_path %></li>
        <li><%= link_to "Conversions", backend_conversions_path %></li>
        <li><%= link_to "Users", backend_users_path %></li>
        <li><%= link_to "Appointments", backend_appointments_path %></li>
        <li><%= link_to "Log out", logout_path, method: "delete" %></li> 
      </ul>
    <% end %>
    </section>
  </nav>
</div>

app/views/layouts/_footer.html.erb
<div class="row">
  <div class="footer small-12 column">
    <div class="row footer-info">
      <div class="medium-4 columns">
        <h4>RECENT ACTIVITY</h4>
        <p>Blog coming soon...</p>
      </div>
      <div class="medium-4 columns">
        <h4>OPENING HOURS</h4>
        <ul>
          <li><i class="fi-clock"></i>MONDAY <span class="opening-hour"><%= t('opening_hours.monday')  %></span></li>
          <li><i class="fi-clock"></i>TUESDAY <span class="opening-hour"><%= t('opening_hours.tuesday')  %></span></li>
          <li><i class="fi-clock"></i>WEDNESDAY <span class="opening-hour"><%= t('opening_hours.wednesday')  %></span></li>
          <li><i class="fi-clock"></i>THURSDAY <span class="opening-hour"><%= t('opening_hours.thursday')  %></span></li>
          <li><i class="fi-clock"></i>FRIDAY <span class="opening-hour"><%= t('opening_hours.friday')  %></span></li>
          <li><i class="fi-clock"></i>SATURDAY <span class="opening-hour"><%= t('opening_hours.saturday')  %></span></li>
          <li><i class="fi-clock"></i>SUNDAY <span class="opening-hour"><%= t('opening_hours.sunday')  %></span></li>
        </ul>
      </div>
      <div class="medium-4 columns">
        <h4>CONTACT INFO</h4>
        <p><i class="fi-map"></i><%= "#{t('contact_details.address.line_1')},
                                      #{t('contact_details.address.line_2')},
                                      #{t('contact_details.address.line_3')},
                                      #{t('contact_details.address.city')},
                                      #{t('contact_details.address.post_code')}" %></p>
          <p><i class="fi-telephone"></i><%= t('contact_details.phone') %></p>
          <p><i class="fi-mail"></i><%= t('contact_details.email') %></p>
          <div class="footer-social-links">
            <%= link_to "", "https://www.facebook.com/VisionHealthFitnessClub", target: "_blank", class: "fi-social-facebook" %>
      <%= link_to "", "#", target: "_blank", class: "fi-social-google-plus" %>
      <%= link_to "", "https://twitter.com/vision_gym", target: "_blank", class: "fi-social-twitter" %>
          </div>
      </div>
    </div>
    <div class="row footer-links">
      <div class="small-12 columns footer-links">
        <ul>
          <li><a href="#">Home</a></li>
          <li><a href="#">Join</a></li>
          <li><a href="#">Classes</a></li>
          <li><a href="#">Opening Times</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<div id="nav-wrapper">
  <div id="nav" class="row">
  <div class="small-12 columns">
    <img src="http://www.visionhealthandfitness.co.uk/logo-small.png" alt="Vision Health and Fitness logo">
  </div>
  <div class="top-social-icons small-12 columns">
      <%= link_to "", "https://www.facebook.com/VisionHealthFitnessClub", target: "_blank", class: "fi-social-facebook" %>
      <%= link_to "", "#", target: "_blank", class: "fi-social-google-plus" %>
      <%= link_to "", "https://twitter.com/vision_gym", target: "_blank", class: "fi-social-twitter" %>
    </div>

  </div>
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>
    <section class="top-bar-section">
      <ul class="right">
        <li class=<%= "#{is_active('static_pages', 'home')}" %>><%= link_to "Home", root_path %></li>
        <li class=<%= "#{is_active('static_pages', 'membership')}" %>><%= link_to "Memberships", membership_path %></li>
        <li class=<%= "#{is_active('static_pages', 'times')}" %>><%= link_to "Opening Times", opening_times_path %></li>
        <li class=<%= "#{is_active('static_pages', 'facilties')}" %>><%= link_to "Facilities", gym_facilities_path %></li>
        <li class="has-dropdown <%= "#{is_active('static_pages', 'classes')}" %>">
        <%= link_to 'Classes', classes_path %>
        <ul class="dropdown">
          <li class=<%= "#{is_active('static_pages', 'ab_solution')}" %>><%= link_to "Ab-solution", classes_ab_solution_path %></li>
          <li class=<%= "#{is_active('static_pages', 'bootcamp')}" %>><%= link_to "Bootcamp", classes_bootcamp_path %></li>
          <li class=<%= "#{is_active('static_pages', 'boxing')}" %>><%= link_to "Boxing", classes_boxing_path %></li>
          <li class=<%= "#{is_active('static_pages', 'circuit_training')}" %>><%= link_to "Circuit Training", classes_circuit_training_path %></li>
          <li class=<%= "#{is_active('static_pages', 'cycle_fit')}" %>><%= link_to "Cycle Fit", classes_cycle_fit_path %></li>
          <li class=<%= "#{is_active('static_pages', 'cycle_pump')}" %>><%= link_to "Cycle Pump", classes_cycle_pump_path %></li>
          <li class=<%= "#{is_active('static_pages', 'hiit')}" %>><%= link_to "HIIT", classes_hiit_path %></li>
          <li class=<%= "#{is_active('static_pages', 'kettle_x_fit')}" %>><%= link_to "Kettle X Fit", classes_kettle_x_fit_path %></li>
          <li class=<%= "#{is_active('static_pages', 'lbt')}" %>><%= link_to "L.B.T", classes_lbt_path %></li>
          <li class=<%= "#{is_active('static_pages', 'mma')}" %>><%= link_to "MMA", classes_mma_path %></li>
          <li class=<%= "#{is_active('static_pages', 'pilates')}" %>><%= link_to "Pilates", classes_pilates_path %></li>
          <li class=<%= "#{is_active('static_pages', 'pilates_hiit')}" %>><%= link_to "Pilates HIIT", classes_pilates_hiit_path %></li>
          <li class=<%= "#{is_active('static_pages', 'pumped')}" %>><%= link_to "Pumped", classes_pumped_path %></li>
          <li class=<%= "#{is_active('static_pages', 'rig_assault')}" %>><%= link_to "Rig Assault", classes_rig_assault_path %></li>
          <li class=<%= "#{is_active('static_pages', 's_and_c')}" %>><%= link_to "S&C", classes_s_and_c_path %></li>
          <li class=<%= "#{is_active('static_pages', 'total_body')}" %>><%= link_to "Total Body", classes_total_body_path %></li>
          <li class=<%= "#{is_active('static_pages', 'trx')}" %>><%= link_to "TRX", classes_trx_path %></li>
          <li class=<%= "#{is_active('static_pages', 'ultimate_endurance')}" %>><%= link_to "Ultimate Endurance", classes_ultimate_endurance_path %></li>
        </ul>
        </li>
        <li class=<%= "#{is_active('static_pages', 'contact')}" %>><%= link_to "Contact", contact_path %></li>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/_under_construction.html.erb
<h2>Page under construction</h2>
<p>This page will be available soon, sorry...</p>
<p>In the meantime you can check out <%= link_to "our facebook page", "https://www.facebook.com/VisionHealthFitnessClub" %>, which is updated regularly and has pictures and info regarding the gym</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Vision Health and Fitness Gateshead" %></title>
    
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr", defer: true %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script>
      (function() {
       var _fbq = window._fbq || (window._fbq = []);
       if (!_fbq.loaded) {
       var fbds = document.createElement('script');
       fbds.async = true;
       fbds.src = '//connect.facebook.net/en_US/fbds.js';
       var s = document.getElementsByTagName('script')[0];
       s.parentNode.insertBefore(fbds, s);
       _fbq.loaded = true;
       }
      })();

      window._fbq = window._fbq || [];
      window._fbq.push(['track', '6008198822987', {'value':'0.00','currency':'GBP'}]);
    </script>
    <noscript>
      <img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=6008198822987&amp;cd[value]=0.00&amp;cd[currency]=GBP&amp;noscript=1" />
    </noscript>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-64335788-1', 'auto', {'siteSpeedSampleRate': 100});
      ga('send', 'pageview');
    </script>
    <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "ExerciseGym",
        "additionalType": "http://www.productontology.org/doc/Boxing",
        "name": "Vision Health and Fitness",
        "legalName": "Vision Health and Fitness Club Limited",
        "alternateName": "Vision Gym",
        "url": "http://visionhealthandfitness.co.uk",
        "logo": "http://visionhealthandfitness.co.uk/logo-small.png",
        "sameAs": [ "https://www.facebook.com/VisionHealthFitnessClub",
                    "https://twitter.com/vision_gym"
                  ],
        "telephone": "0191 447 6919",
        "email": "memberships@visionhealthandfitness.co.uk",
        "description": "Gym offers full weights area, free weight section, cardio suite, aerobics studio, boxing studio, sports therapists.",
        "address": {
          "@type": "PostalAddress",
          "addressLocality": "Swalwell",
          "addressRegion": "Gateshead",
          "postalCode": "NE16 3DZ",
          "streetAddress": "Vision Health and Fitness, Market Lane",
          "addressCountry": "England"
          },
          "openingHours": [ "Mo-Fr 07:00-21:00",
                            "Sa 08:00-17:00",
                            "Su 09:00-14:00"
                          ],
          "geo": {
            "@type": "GeoCoordinates",
            "latitude": "54.9546392",
            "longitude": "-1.6803238",
            "elevation": "14.80 m"
          }                                                           }
        }                                                              }   
    </script>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
    <%= render 'layouts/footer' %>

  <script type="text/javascript">
    function downloadJSAtOnload() {
    var element = document.createElement("script");
    element.src = "fonts.js";
    document.body.appendChild(element);
    }
    if (window.addEventListener)
      window.addEventListener("load", downloadJSAtOnload, false);
    else if (window.attachEvent)
      window.attachEvent("onload", downloadJSAtOnload);
    else window.onload = downloadJSAtOnload;
  </script>

  </body>
</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Vision Health and Fitness Gateshead" %></title>
    
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr", defer: true %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/backend_nav' %>
  <div class="row">
    <div class="small-12 medium-8 large-6 columns small-centered">
    <%= yield %>
  </div>
</div>

    </body>